Predmet: Inteligentná analýza údajov
Cvičenie: Piatok 8:00
Cvičiaci: Ing. Ondrej Kaššák, PhD.
Tím: Miroslav Ivan
     Denis Ivanics
Č. datasetu : 2

In [5]:
#Miroslav - priprava dokumentu na pracu
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import scipy.stats as stats

In [9]:
#Miroslav - otvorenie csvcka
filepath = 'Data/other_train.csv'
data = pd.read_csv(filepath)

In [17]:
# Miroslav - chcem zistit ako to vyzera, uz som pozeral ze nas zaujima medical info a budeme to musiet vytiahnut a spracovat
data.head()

,Unnamed: 0,name,address,kurtosis_oxygen,occupation,marital-status,pregnant,education-num,relationship,std_oxygen,...,fnlwgt,class,income,medical_info,native-country,capital-loss,mean_oxygen,hours-per-week,race,workclass
0,0,James Pearl,"13640 King Way\r\nCandacestad, CO 48501",13.32836013,Adm-clerical,Never-married,f,9.0,Own-child,11.739964,...,176711.0,0.0,<=50K,"{'mean_glucose':'120.0859375','std_glucose':'4...",United-States,0.0,1.513378,40.0,White,Private
1,1,Douglas Staten,"1854 Nicole Courts\r\nSouth Jeremyside, NC 39011",2.651634775,Tech-support,Married-civ-spouse,f,10.0,Husband,56.571626,...,106103.0,1.0,>50K,"{'mean_glucose':'49.9609375','std_glucose':'30...",United-States,0.0,22.392977,60.0,White,Self-emp-inc
2,2,Kenneth Noboa,Unit 5904 Box 6980\r\nDPO AP 20958,8.719683507000001,Exec-managerial,Married-civ-spouse,f,10.0,Husband,20.870270,...,38622.0,0.0,<=50K,"{'mean_glucose':'131.5','std_glucose':'51.2471...",United-States,0.0,3.093645,40.0,White,Self-emp-not-inc
3,3,William Newton,37221 Diana Well Apt. 813\r\nSouth Charlesport...,10.16590541,Prof-specialty,Married-civ-spouse,f,9.0,Husband,19.696000,...,163392.0,0.0,>50K,"{'mean_glucose':'105.96875','std_glucose':'42....",United-States,0.0,2.125418,48.0,Amer-Indian-Eskimo,Private
4,4,Richard Steffes,"3576 David Light\r\nKirkport, VA 24595",-0.307349352,Exec-managerial,Married-civ-spouse,f,10.0,Husband,82.579219,...,342448.0,1.0,>50K,"{'mean_glucose':'21.734375','std_glucose':'30....",United-States,0.0,146.533445,55.0,White,Private

In [52]:
#Miroslav - vytiahnutie medical info do zvlast tabulky
#Toto mozno ide spravit mudrejsie
medinfo = data.loc[:,'medical_info']
medinfo.head()

0    {'mean_glucose':'120.0859375','std_glucose':'4...
1    {'mean_glucose':'49.9609375','std_glucose':'30...
2    {'mean_glucose':'131.5','std_glucose':'51.2471...
3    {'mean_glucose':'105.96875','std_glucose':'42....
4    {'mean_glucose':'21.734375','std_glucose':'30....
Name: medical_info, dtype: object

In [51]:
#Miroslav - zmena object na string
#treba doriesit este

medinfo = str(medinfo)
medinfo.replace('{', ' ')
medinfo.replace('}','\n')
print(medinfo)

0       {'mean_glucose':'120.0859375','std_glucose':'4...
1       {'mean_glucose':'49.9609375','std_glucose':'30...
2       {'mean_glucose':'131.5','std_glucose':'51.2471...
3       {'mean_glucose':'105.96875','std_glucose':'42....
4       {'mean_glucose':'21.734375','std_glucose':'30....
5       {'mean_glucose':'113.421875','std_glucose':'48...
6       {'mean_glucose':'103.65625','std_glucose':'52....
7       {'mean_glucose':'140.0234375','std_glucose':'5...
8       {'mean_glucose':'129.875','std_glucose':'52.43...
9       {'mean_glucose':'85.4140625','std_glucose':'37...
10      {'mean_glucose':'114.5','std_glucose':'47.3403...
11      {'mean_glucose':'105.453125','std_glucose':'42...
12      {'mean_glucose':'43.0','std_glucose':'28.46653...
13      {'mean_glucose':'99.0234375','std_glucose':'34...
14      {'mean_glucose':'122.328125','std_glucose':'52...
15      {'mean_glucose':'92.71875','std_glucose':'43.9...
16      {'mean_glucose':'35.4296875','std_glucose':'35...
17      {'mean_glucose':'103.6796875','std_glucose':'3...
18      {'mean_glucose':'126.0','std_glucose':'66.4947...
19      {'mean_glucose':'16.5390625','std_glucose':'35...
20      {'mean_glucose':'82.703125','std_glucose':'38....
21      {'mean_glucose':'81.0546875','std_glucose':'43...
22      {'mean_glucose':'115.421875','std_glucose':'46...
23      {'mean_glucose':'52.609375','std_glucose':'44....
24      {'mean_glucose':'-11956.25','std_glucose':'51....
25      {'mean_glucose':'115.5','std_glucose':'50.6101...
26      {'mean_glucose':'-11028.90625','std_glucose':'...
27      {'mean_glucose':'120.640625','std_glucose':'53...
28      {'mean_glucose':'136.0234375','std_glucose':'5...
29      {'mean_glucose':'137.109375','std_glucose':'58...
                              ...
3953    {'mean_glucose':'32.34375','std_glucose':'27.6...
3954    {'mean_glucose':'127.5625','std_glucose':'52.2...
3955    {'mean_glucose':'46.5703125','std_glucose':'38...
3956    {'mean_glucose':'116.8515625','std_glucose':'5...
3957    {'mean_glucose':'114.3515625','std_glucose':'4...
3958    {'mean_glucose':'127.0390625','std_glucose':'5...
3959    {'mean_glucose':'91.5859375','std_glucose':'48...
3960    {'mean_glucose':'161.3046875','std_glucose':'5...
3961    {'mean_glucose':'85.3984375','std_glucose':'44...
3962    {'mean_glucose':'108.3203125','std_glucose':'7...
3963    {'mean_glucose':'101.6875','std_glucose':'47.0...
3964    {'mean_glucose':'92.953125','std_glucose':'35....
3965    {'mean_glucose':'108.2109375','std_glucose':'4...
3966    {'mean_glucose':'101.2421875','std_glucose':'3...
3967    {'mean_glucose':'124.4921875','std_glucose':'4...
3968    {'mean_glucose':'7.0625','std_glucose':'33.628...
3969    {'mean_glucose':'114.2421875','std_glucose':'4...
3970    {'mean_glucose':'118.265625','std_glucose':'54...
3971    {'mean_glucose':'75.1015625','std_glucose':'35...
3972    {'mean_glucose':'78.8671875','std_glucose':'36...
3973    {'mean_glucose':'109.796875','std_glucose':'42...
3974    {'mean_glucose':'85.96875','std_glucose':'45.8...
3975    {'mean_glucose':'138.875','std_glucose':'51.22...
3976    {'mean_glucose':'111.8828125','std_glucose':'4...
3977    {'mean_glucose':'82.875','std_glucose':'37.919...
3978    {'mean_glucose':'113.3671875','std_glucose':'5...
3979    {'mean_glucose':'29.3671875','std_glucose':'36...
3980    {'mean_glucose':'9192.1875','std_glucose':'45....
3981    {'mean_glucose':'114.8203125','std_glucose':'4...
3982    {'mean_glucose':'10314.0625','std_glucose':'42...
Name: medical_info, Length: 3983, dtype: object